
# This is a basic workflow to help you get started with Actions

name: Package Tools

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  PackgeTools:
    runs-on: ubuntu-latest
    env:
      MAJOR_VERSION: 0
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - run: |
        find Assets/PFCTools/ -name \*.meta >> metaList
    - run: mkdir package

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'package/PFCTools.unitypackage'
        include-files: metaList
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Latest"
        prerelease: false
        title: "Latest Release"
        files: |
            package/PFCTools.unitypackage
    - name: Version release file
      run: mv "package/PFCTools.unitypackage" "package/PFCTools-v${MAJOR_VERSION}.${GITHUB_RUN_NUMBER}.unitypackage"
    - name: Echo files
      run: ls package/
    - name: Send file to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: package/*
    - name: "Parse release name"
      id: get-release-name
      run: "echo ::set-output name=name::${RELEASE:-$TAG}"
      env:
        RELEASE: ${{ github.event.release.name }}
        TAG: ${{ github.event.release.tag_name }}
    - name: "Crosspost changelog to Discord"
      uses: kludge-cs/gitcord-release-changelogger@v3.0.0
      with:
        release-body: ${{ github.event.release.body }}
        release-name: ${{ steps.get-release-name.outputs.name }}
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
