
# This is a basic workflow to help you get started with Actions

name: Package Tools

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  PackgeTools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - run: |
        find Source/ -name \*.meta >> metaList
    - run: mkdir package

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'package/PFCTools.unitypackage'
        include-files: metaList
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "Latest"
        prerelease: false
        title: "Latest Release"
        files: |
            package/PFCTools.unitypackage
    - name: Version release file
      run: mv package/PFCTools.unitypackage package/PFCTools-$GITHUB_RUN_NUMBER.unitypackage
    - name: Send file to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: package/PFCTools-$GITHUB_RUN_NUMBER.unitypackage
